create table t_nimbus_alerta (
   id_alerta      number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL ,
   ds_risco       varchar2(20) not null,
   ds_tipo        varchar2(20) not null,
   ds_mensagem    varchar2(250) not null,
   horario_alerta date not null,
   id_bairro      number(9) not null
);

alter table t_nimbus_alerta add constraint t_nimbus_alerta_pk primary key ( id_alerta );

create table t_nimbus_bairro (
   id_bairro      number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_bairro  varchar2(100) not null,
   id_cidade      number(9) not null,
   id_localizacao number(9) not null
);


alter table t_nimbus_bairro add constraint t_nimbus_bairro_pk primary key ( id_bairro );

create table t_nimbus_cidade (
   id_cidade number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_cidade varchar2(100) not null,
   id_estado number(9) not null
);

alter table t_nimbus_cidade add constraint t_nimbus_cidade_pk primary key ( id_cidade );

create table t_nimbus_endereco (
   id_endereco number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nr_cep      char(8) not null,
   id_bairro   number(9) not null,
   nm_logradouro  varchar2(100) not null,
   nr_logradouro   number(5)   
);

alter table t_nimbus_endereco add constraint t_nimbus_endereco_pk primary key ( id_endereco );

alter table t_nimbus_endereco
   add constraint ck_cep check ( length(nr_cep) = 8 );

create table t_nimbus_estado (
   id_estado number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_estado varchar2(50) not null,
   id_pais   number(9) not null
);

alter table t_nimbus_estado add constraint t_nimbus_estado_pk primary key ( id_estado );

create table t_nimbus_gp_endereco (
   id_gp_endereco number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_grupo       varchar2(100) not null,
   id_usuario     number(9) not null,
   id_endereco    number(9) not null
);

alter table t_nimbus_gp_endereco add constraint t_nimbus_gp_endereco_pk primary key ( id_gp_endereco );

create table t_nimbus_localizacao (
   id_localizacao number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nr_longitude   number(6) not null,
   nr_latitude    number(6) not null
);


alter table t_nimbus_localizacao add constraint t_nimbus_localizacao_pk primary key ( id_localizacao );

create table t_nimbus_pais (
   id_pais number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_pais varchar2(50) not null
);

alter table t_nimbus_pais add constraint t_nimbus_pais_pk primary key ( id_pais );

create table t_nimbus_previsao (
   id_previsao         number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_hora             varchar2(50) not null,
   nr_temperatura      number(20) not null,
   nr_chuva            number(20) not null,
   nr_codigo_chuva     number(20) not null,
   nr_velocidade_vento number(20) not null,
   nr_rajada_vento     number(20) not null,
   nr_umidade          number(20) not null,
   id_bairro           number(9) not null
);

alter table t_nimbus_previsao add constraint t_nimbus_previsao_pk primary key ( id_previsao );

create table t_nimbus_usuario (
   id_usuario number(9) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
   nm_usuario varchar2(50) not null,
   ds_email   varchar2(50) not null,
   senha      varchar2(12) not null
);

alter table t_nimbus_usuario add constraint t_nimbus_usuario_pk primary key ( id_usuario );

alter table t_nimbus_estado
   add constraint relation_1 foreign key ( id_pais )
      references t_nimbus_pais ( id_pais );

alter table t_nimbus_gp_endereco
   add constraint relation_10 foreign key ( id_endereco )
      references t_nimbus_endereco ( id_endereco );

alter table t_nimbus_cidade
   add constraint relation_2 foreign key ( id_estado )
      references t_nimbus_estado ( id_estado );

alter table t_nimbus_previsao
   add constraint relation_23 foreign key ( id_bairro )
      references t_nimbus_bairro ( id_bairro );

alter table t_nimbus_alerta
   add constraint relation_24 foreign key ( id_bairro )
      references t_nimbus_bairro ( id_bairro );

alter table t_nimbus_bairro
   add constraint relation_3 foreign key ( id_cidade )
      references t_nimbus_cidade ( id_cidade );

alter table t_nimbus_endereco
   add constraint relation_4 foreign key ( id_bairro )
      references t_nimbus_bairro ( id_bairro );

alter table t_nimbus_bairro
   add constraint relation_7 foreign key ( id_localizacao )
      references t_nimbus_localizacao ( id_localizacao );

alter table t_nimbus_gp_endereco
   add constraint relation_9 foreign key ( id_usuario )
      references t_nimbus_usuario ( id_usuario );