DROP TABLE t_nimbus_alerta CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_gp_endereco CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_usuario CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_endereco CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_bairro CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_cidade CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_estado CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_pais CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_localizacao CASCADE CONSTRAINTS;
DROP TABLE t_nimbus_previsao CASCADE CONSTRAINTS;





